-- Base inicial de locacoes reconstruida a partir dos contratos analisados.
-- Valores-base nao confirmados como aluguel atual ficam zerados e sinalizados para revisao.

insert into public.real_estate_imoveis (
  id, nome, unidade_ocupante, marca, endereco, status, modalidade,
  revisao_pendente, contrato_numero, area_m2, locador, locataria,
  cnpj_locataria, centro_custo, contrato_inicio, contrato_fim,
  valor_aluguel, investimento_locador, investidores, indice_reajuste,
  data_reajuste, garantia, multa_aviso, contrato_docs, obrigacoes,
  aditivos, devolucao, observacoes
) values
(
  'b0000000-0000-4000-8000-000000000001',
  'Marapendi - Rua Sylvio Pinto',
  'Cubo Global School Marapendi / Global Tree Marapendi',
  'CUBO',
  'Rua Sylvio Pinto, 135 - Bosque Marapendi, Rio de Janeiro - RJ',
  'Atencao', 'Built to suit', true, '', 6702.50,
  'DLS 3 Administradora Ltda.', 'Colegio e Curso Ao Cubo S.A.',
  '23.075.186/0001-43', '', '2024-04-01', '2035-03-31',
  0, 11724000.00,
  '[{"nome":"DLS 3 Administradora Ltda.","detalhe":"Locadora e investidora; aporte contratual de ate R$ 11.724.000,00"}]'::jsonb,
  'IPCA - somente variacao positiva', '2027-04-01', 'Raiz Educacao S.A. como fiadora',
  'Aviso de 120 dias ao fim da vigencia; built to suit com regras proprias de rescisao',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Contrato built to suit: terreno de 6.702,50 m2 e predio projetado de aproximadamente 3.033,24 m2. Aluguel-base contratual de R$ 250.000,00; o valor corrente precisa ser conciliado com os reajustes e eventuais majoracoes ligadas ao aporte. Fonte local: contrato Ao Cubo x DLS 3 - Rua Sylvio Pinto.'
),
(
  'b0000000-0000-4000-8000-000000000002',
  'Leonardo da Vinci Gama - Rua Aurora',
  'Colegio Leonardo da Vinci Gama',
  'LEONARDO DA VINCI',
  'Rua Aurora, 695 - Marechal Rondon, Canoas - RS',
  'Atencao', 'Built to suit', true, '', 0,
  'Dallasanta; L F Promocoes; A.H. Incorporacoes; Salvadori; Risa; EPL',
  'Operacao Leonardo da Vinci / Raiz Educacao', '', '',
  '2020-06-01', '2030-05-31', 0, 4500000.00,
  '[{"nome":"Dallasanta Empreendimentos e Incorporacoes Ltda.","detalhe":"20%"},{"nome":"L F Promocoes Servicos e Representacoes Ltda.","detalhe":"20%"},{"nome":"A.H. Incorporacoes Eireli","detalhe":"20%"},{"nome":"Salvadori Incorporacoes e Participacoes Ltda.","detalhe":"20%"},{"nome":"Risa Administracao e Participacoes Ltda.","detalhe":"10%"},{"nome":"EPL Assessoria, Consultoria, Empreendimentos, Participacoes e Investimentos Ltda.","detalhe":"10%"}]'::jsonb,
  'IGP-M', '2027-06-01', '',
  'Renovacao automatica; aviso de 5 meses para nao renovar',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Contrato built to suit com obras arcadas pelos locadores ate R$ 4.500.000,00. Aluguel-base contratual de R$ 80.000,00; atualizar o valor corrente antes de usa-lo em orcamento. Fonte local: contrato CLV Gama x locadores - Rua Aurora.'
),
(
  'b0000000-0000-4000-8000-000000000003',
  'Colegio Uniao - Rua Dr. Lauro de Oliveira',
  'Colegio e Curso Uniao',
  'UNIAO',
  'Rua Dr. Lauro de Oliveira, 71 - Rio Branco, Porto Alegre - RS',
  'Ativo', 'Built to suit', false, '', 6688.58,
  'DLS 17 Incorporadora Ltda.', 'Colegio e Curso Uniao Ltda.',
  '58.241.128/0001-27', '', '2024-12-03', '2034-12-02',
  45962.40, 0,
  '[{"nome":"DLS 17 Incorporadora Ltda.","detalhe":"Locadora; aquisicao do imovel para a operacao, sem aporte de obra quantificado no contrato analisado"}]'::jsonb,
  'IPCA - somente variacao positiva', '2026-12-03', 'Raiz Educacao S.A. como fiadora',
  'Built to suit; multa de R$ 5.000.000,00 em caso de rescisao antecipada, proporcional na forma contratual',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Aluguel-base do contrato: R$ 44.000,00. Valor de 2026 informado no historico orcamentario: R$ 45.962,40. O contrato e built to suit pela aquisicao dedicada do imovel, mas nao foi identificado aporte de obra quantificado.'
),
(
  'b0000000-0000-4000-8000-000000000004',
  'Unificado Zona Sul - Rua Teresa Cristo',
  'Colegio Unificado Zona Sul',
  'UNIFICADO',
  'Rua Teresa Cristo, 115 - Tristeza, Porto Alegre - RS',
  'Atencao', 'Built to suit', true, '', 0,
  'Dallasanta Empreendimentos e Incorporacoes Ltda.',
  'Grupo Educacional Unificado Ltda. / Raiz Sul Empreendimentos em Educacao S.A.',
  '89.409.825/0001-78', '', '2021-08-17', '2031-08-16',
  0, 2500000.00,
  '[{"nome":"Dallasanta Empreendimentos e Incorporacoes Ltda.","detalhe":"Locadora e investidora; obras ate R$ 2.500.000,00"}]'::jsonb,
  'IPCA', '2027-08-17', '', 'Renovacao automatica; aviso de 5 meses para nao renovar',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Contrato built to suit com reforma financiada pelo locador ate R$ 2.500.000,00. Aluguel-base contratual de R$ 40.000,00; atualizar o valor corrente. O contrato menciona Rua Teresa Cristo, 60, enquanto o cadastro operacional da unidade usa o numero 115; divergencia mantida para revisao.'
),
(
  'b0000000-0000-4000-8000-000000000005',
  'Americano Cabral - Rua Cabral',
  'Colegio Americano Cabral',
  'AMERICANO',
  'Rua Cabral, 521 - Rio Branco, Porto Alegre - RS',
  'Em renovacao', 'Locacao comum', true, '', 0,
  'DLS 5 Administradora e Incorporadora Ltda.',
  'Sociedade Educacional Leonardo da Vinci Ltda.', '92.845.437/0001-44', '',
  '2022-01-01', '2026-12-31', 0, 0, '[]'::jsonb,
  'Indice a confirmar no contrato vigente', null, 'Raiz Educacao S.A. como fiadora', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Aluguel-base contratual de R$ 93.000,00. A vigencia original termina em dezembro de 2026; confirmar renovacao, indice e aluguel corrente antes de usar o registro em orcamentos.'
),
(
  'b0000000-0000-4000-8000-000000000006',
  'Leonardo da Vinci - IPA Predio C',
  'Colegio Leonardo da Vinci Alfa',
  'LEONARDO DA VINCI',
  'IPA - Predio C, Porto Alegre - RS',
  'Atencao', 'Locacao comum', true, '', 0,
  'DLS 17 Incorporadora Ltda.', 'Colegio Leonardo da Vinci Ltda.',
  '09.262.835/0001-94', '', '2025-02-26', '2030-02-25',
  0, 0, '[]'::jsonb,
  'IPCA - somente variacao positiva', '2027-02-26', 'Raiz Educacao S.A. como fiadora', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Aluguel nominal de R$ 200.000,00 com descontos escalonados: R$ 120.000,00 por 12 meses, depois R$ 80.000,00 por 12 meses e R$ 40.000,00 por 12 meses, sujeitos as regras de correcao do contrato. O custo corrente deve ser calculado pela fase vigente e confirmado.'
),
(
  'b0000000-0000-4000-8000-000000000007',
  'Escolas Integradas - Rua Correia de Araujo',
  'Escolas Integradas Raiz',
  'RAIZ',
  'Rua Correia de Araujo, 131 - Barra da Tijuca, Rio de Janeiro - RJ',
  'Ativo', 'Locacao comum', false, '000504/3', 0,
  'TRML Participacao e Administracao Ltda. / Expansao Rio Administradora de Imoveis Ltda.',
  'Escolas Integradas Raiz Ltda.', '07.499.961/0001-31', '',
  '2026-05-01', '2031-04-30', 30000.00, 0, '[]'::jsonb,
  'IPCA', '2027-05-01', 'Raiz Educacao S.A. como fiadora', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Aluguel mensal de R$ 30.000,00, acrescido das taxas ordinarias do imovel. Renovacao automatica por igual periodo, salvo manifestacao em contrario.'
),
(
  'b0000000-0000-4000-8000-000000000008',
  'Residencia corporativa - Av. Adilson Seroa da Motta',
  'Corporativo',
  'RAIZ',
  'Av. Adilson Seroa da Motta, 231, apto. 104 - Barra da Tijuca, Rio de Janeiro - RJ',
  'Ativo', 'Residencial corporativa', false, '', 0,
  'Rodrigo de Menezes Gomes e Fernanda Escarlate Tavares Gomes',
  'Alfredo Portugal de Paula Rocha e Assaiah Moreira da Costa Portugal', '', '',
  '2025-11-25', '2028-05-24', 7000.00, 0, '[]'::jsonb,
  'IGP-M', '2026-11-25', '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Contrato residencial firmado diretamente pelos ocupantes. Manter separado dos contratos operacionais das escolas.'
),
(
  'b0000000-0000-4000-8000-000000000009',
  'Matriz Retiro - Rua Retiro dos Artistas',
  'Matriz Educacao Retiro',
  'MATRIZ',
  'Rua Retiro dos Artistas, 812 - Pechincha, Rio de Janeiro - RJ',
  'Atencao', 'Locacao comum', true, '', 0,
  'Evolution Participacoes', 'Matriz Educacao', '', '',
  '2024-08-01', null, 89441.44, 0, '[]'::jsonb,
  'IPCA - somente variacao positiva', '2026-08-01', '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Valor de R$ 89.441,44 validado para o primeiro reajuste: base de R$ 85.000,00 atualizada em 5,225222% pelo IPCA de agosto/2024 a julho/2025. O aniversario de agosto/2026 exige nova atualizacao do valor corrente.'
),
(
  'b0000000-0000-4000-8000-000000000010',
  'Matriz Taquara - Rua Padre Ventura',
  'Matriz Educacao Taquara',
  'MATRIZ',
  'Rua Padre Ventura, 200 - Taquara, Rio de Janeiro - RJ',
  'Atencao', 'Locacao comum', true, '', 0,
  'Novo Horizonte / locadores do imovel', 'Matriz Educacao', '', '',
  null, null, 81172.97, 0, '[]'::jsonb,
  'IGP-M', '2027-01-01', '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Valor contratual estimado para 2026: R$ 81.172,97. O pagamento de R$ 76.994,04 parece corresponder aos 95% destinados aos locadores; o contrato separa 5% para administracao. Revisar com o comprovante e a memoria de calculo.'
),
(
  'b0000000-0000-4000-8000-000000000011',
  'Global Tree Peninsula - Rua dos Jacarandas',
  'Global Tree Peninsula',
  'GLOBAL TREE',
  'Rua dos Jacarandas da Peninsula, 85/1101 - Barra da Tijuca, Rio de Janeiro - RJ',
  'Atencao', 'Locacao comum', true, '', 0,
  'Novo Horizonte', 'Global Tree / Creche Ipe', '', '',
  '2023-01-01', null, 145499.85, 0, '[]'::jsonb,
  'IPCA', '2027-01-01', '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Historico: contrato original de R$ 109.540,00; aditivos para R$ 113.021,00, R$ 130.586,00 e R$ 133.236,00. O valor cobrado de R$ 145.499,85 e materialmente compativel com os reajustes, mas a formula exata depende da memoria de calculo do locador. Confirmar tambem a numeracao 85/1101.'
),
(
  'b0000000-0000-4000-8000-000000000012',
  'Sarah Dawsey Tijuca - Rua Jose Higino',
  'Sarah Dawsey Tijuca',
  'SARAH DAWSEY',
  'Rua Jose Higino, 240 - Tijuca, Rio de Janeiro - RJ',
  'Atencao', 'Locacao principal com sublocacao', true, '', 0,
  'Lar da Crianca Israelita', 'Colegio e Curso Ao Cubo S.A.', '', '',
  null, null, 0, 0, '[]'::jsonb,
  'Indice e valor corrente a confirmar', null, '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'O Cubo continua responsavel perante o proprietario. O Centro de Educacao Contemporanea Tijuca suporta economicamente o aluguel pela sublocacao e tambem os encargos previstos. Confirmar a autorizacao formal do proprietario e os valores correntes.'
),
(
  'b0000000-0000-4000-8000-000000000013',
  'Barra Golf - Ruy Antunes / Costa Nunes',
  'Cubo Global School Barra Golf / Global Tree Barra Golf',
  'CUBO',
  'Rua Professor Costa Nunes, 50 / Av. Ruy Antunes Correa - Barra da Tijuca, Rio de Janeiro - RJ',
  'Ativo', 'Locacao comum', false, '', 4248.20,
  'WJM e Rio Zhen', 'Colegio e Curso Ao Cubo S.A.', '23.075.186/0001-43', '',
  null, null, 229850.00, 2700000.00,
  '[{"nome":"WJM e Rio Zhen","detalhe":"Locadores; aditivo registra aporte adicional de R$ 2.700.000,00"}]'::jsonb,
  'Indice a confirmar no contrato vigente', null, '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'O aditivo incorporou lote da Rua Professor Costa Nunes, acrescentou R$ 8.000,00 ao aluguel e R$ 29.700,00 pela remuneracao de aporte adicional de R$ 2.700.000,00. Valor contratual consolidado analisado: R$ 229.850,00. O contrato nao define o rateio interno entre Cubo e Global Tree.'
),
(
  'b0000000-0000-4000-8000-000000000014',
  'QI Tijuca - Rua Ibituruna',
  'Colegio QI Tijuca',
  'QI',
  'Rua Ibituruna, 37 - Tijuca, Rio de Janeiro - RJ',
  'Atencao', 'Locacao comum', true, '', 0,
  'Colegio TTH Bar-Ilan / locadores do imovel', 'QI', '', '',
  null, null, 0, 0, '[]'::jsonb,
  'IGP-M', null, '', '',
  '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
  '{"status":"Sem devolucao prevista","previsao":"","valor_estimado":0,"observacoes":"","trs":[],"docs":[]}'::jsonb,
  'Boleto analisado com divergencia: valor impresso de R$ 145.330,20 e linha digitavel de R$ 138.671,81. A taxa implicita nao coincidiu com o IGP-M aplicavel. Nao usar valor corrente sem comprovante bancario, aditivo vigente e memoria de calculo.'
)
on conflict (id) do nothing;

