create table if not exists public.real_estate_sublocacoes (
  id uuid primary key default gen_random_uuid(),
  fonte_chave text not null unique,
  tipo text not null default 'Cantina',
  marca text not null default 'RAIZ',
  unidade text not null,
  localidade text not null default '',
  sublocatario text not null,
  email text not null default '',
  telefone text not null default '',
  status text not null default 'Ativo',
  vigencia_texto text not null default '',
  contrato_inicio date,
  contrato_fim date,
  regra_cobranca text not null default '',
  valor_referencia numeric not null default 0,
  forma_pagamento text not null default '',
  emissao text not null default '',
  dia_vencimento integer,
  contrato_status text not null default 'Nao confirmado',
  documentacao_status text not null default 'Nao confirmado',
  documento_url text not null default '',
  pasta_url text not null default '',
  cobrancas jsonb not null default '[]'::jsonb,
  revisao_pendente boolean not null default false,
  divergencias jsonb not null default '[]'::jsonb,
  observacoes text not null default '',
  fonte text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint real_estate_sublocacoes_dia_vencimento_check
    check (dia_vencimento is null or dia_vencimento between 1 and 31)
);

create index if not exists real_estate_sublocacoes_marca_idx on public.real_estate_sublocacoes(marca);
create index if not exists real_estate_sublocacoes_unidade_idx on public.real_estate_sublocacoes(unidade);
create index if not exists real_estate_sublocacoes_sublocatario_idx on public.real_estate_sublocacoes(sublocatario);
create index if not exists real_estate_sublocacoes_status_idx on public.real_estate_sublocacoes(status);
create index if not exists real_estate_sublocacoes_revisao_idx on public.real_estate_sublocacoes(revisao_pendente);
create index if not exists real_estate_sublocacoes_cobrancas_gin_idx on public.real_estate_sublocacoes using gin(cobrancas);

alter table public.real_estate_sublocacoes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'real_estate_sublocacoes'
      and policyname = 'real_estate_sublocacoes_select_authenticated'
  ) then
    create policy real_estate_sublocacoes_select_authenticated
      on public.real_estate_sublocacoes
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'real_estate_sublocacoes'
      and policyname = 'real_estate_sublocacoes_write_authenticated'
  ) then
    create policy real_estate_sublocacoes_write_authenticated
      on public.real_estate_sublocacoes
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

comment on table public.real_estate_sublocacoes is
  'Cadastro independente de Real Estate para sublocacoes de cantinas, contratos, documentacao e cobrancas.';

insert into public.real_estate_sublocacoes (
  fonte_chave, marca, unidade, localidade, sublocatario, email, telefone,
  status, vigencia_texto, contrato_fim, regra_cobranca, valor_referencia,
  forma_pagamento, emissao, dia_vencimento, contrato_status,
  documentacao_status, documento_url, pasta_url, cobrancas,
  revisao_pendente, divergencias, observacoes, fonte
)
values
  ('cantina|cubo|barra','CUBO','Cubo Barra','Rio de Janeiro','Tia Lana','lanaselma.2020@gmail.com; cantinatialana@gmail.com','21 98723-1086','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 4,40 por aluno de curso',1096.60,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1aegyEPaHZljuphjtUGdZFyDGYMUSc8Sn/view','https://drive.google.com/drive/folders/1l3-8mOa5cB7kDd6LZP2bwr5KokrqSHjT','[{"competencia":"2026-08","valor":1096.60,"vencimento":"2026-08-15","referencia":"621753","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|cubo|botafogo','CUBO','Cubo Botafogo','Rio de Janeiro','Tia Lana','lanaselma.2020@gmail.com; cantinatialana@gmail.com','21 98723-1086','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 4,40 por aluno de curso',1278.60,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1s_7YDWC0x1ImO1mW1FqWMsvu0hTCZivP/view','https://drive.google.com/drive/folders/1l3-8mOa5cB7kDd6LZP2bwr5KokrqSHjT','[{"competencia":"2026-08","valor":1278.60,"vencimento":"2026-08-15","referencia":"621754","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|qi|rio-2','QI','QI Rio 2','Rio de Janeiro','Tia Lana','lanaselma.2020@gmail.com; cantinatialana@gmail.com','21 98723-1086','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 4,40 por aluno de curso',1894.20,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1ecVNHTD-C_bjYUULkSl2rb-mxqEr-86h/view','https://drive.google.com/drive/folders/1l3-8mOa5cB7kDd6LZP2bwr5KokrqSHjT','[{"competencia":"2026-08","valor":1894.20,"vencimento":"2026-08-15","referencia":"730987","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|qi|recreio','QI','QI Recreio','Rio de Janeiro','Tia Lana','lanaselma.2020@gmail.com; cantinatialana@gmail.com','21 98723-1086','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 4,40 por aluno de curso',1269.60,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1qGUwY76cW69USEbXXPW60reVMoXgRSKd/view','https://drive.google.com/drive/folders/1l3-8mOa5cB7kDd6LZP2bwr5KokrqSHjT','[{"competencia":"2026-08","valor":1269.60,"vencimento":"2026-08-15","referencia":"568049","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|qi|freguesia','QI','QI Freguesia','Rio de Janeiro','Emporio Araguaia','vitor.zavarize@gmail.com; antoniazavarize@yahoo.com.br','21 96449-9900','Ativo','1 ano','2026-12-31','R$ 4,40 Fund. I; R$ 8,40 Fund. II, EM e curso',1008.60,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1d8LYRfeDDJaxf8JdR7dzw06YwPUTur6A/view','https://drive.google.com/drive/folders/183nYWVO3rNIjik2yVjOnTV3aDviIY-Be','[{"competencia":"2026-08","valor":1008.60,"vencimento":"2026-08-15","referencia":"730986","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas o contrato foi localizado no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|sao-joao-de-meriti','MATRIZ','Matriz Sao Joao de Meriti','Rio de Janeiro','Emporio Araguaia','vitor.zavarize@gmail.com; antoniazavarize@yahoo.com.br','21 96449-9900','Ativo','1 ano','2026-12-31','R$ 4,00 Fund. I; R$ 8,00 Fund. II, EM e curso',0,'Emissao de boleto','1a semana do mes',15,'Assinado','Informada como completa','https://drive.google.com/file/d/1a9wTR2y20yO6PWA3_HLyJHOi2ipGibGk/view','https://drive.google.com/drive/folders/183nYWVO3rNIjik2yVjOnTV3aDviIY-Be','[]',true,'["Sem lancamento de agosto localizado na planilha mensal."]','','Controle de Overdue 2026; Drive'),
  ('cantina|matriz|nova-iguacu','MATRIZ','Matriz Nova Iguacu','Rio de Janeiro','Eraldo Lanches','eraldodesouzamatheus@gmail.com','21 99426-7363','Ativo','1 ano','2026-12-31','R$ 7,00 por aluno regular; R$ 3,00 por aluno de curso livre',1526.00,'Emissao de boleto','1a semana do mes',15,'Assinado','Informada como completa','https://drive.google.com/file/d/1L8vF0X0eazpU35EDRbgr9C4lm1iIiMRn/view','https://drive.google.com/drive/folders/1rw-CN0mzYDvq8D-MppFK2tFdtg2-6zDt','[{"competencia":"2026-08","valor":1526.00,"vencimento":"2026-08-15","referencia":"810831","status":"Lancado"}]',false,'[]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|qi|metropolitano','QI','QI Metropolitano','Rio de Janeiro','Eraldo Lanches','eraldodesouzamatheus@gmail.com','21 99426-7363','Ativo','1 ano','2026-12-31','R$ 4,00 Fund. I; R$ 8,00 Fund. II, EM e curso',1605.80,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/17IffcC9DBnPirB_PdB2nWVZYRRlMdDud/view','https://drive.google.com/drive/folders/1rw-CN0mzYDvq8D-MppFK2tFdtg2-6zDt','[{"competencia":"2026-08","valor":1605.80,"vencimento":"2026-08-15","referencia":"184796","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|qi|tijuca','QI','QI Tijuca','Rio de Janeiro','Eraldo Lanches','eraldodesouzamatheus@gmail.com','21 99426-7363','Ativo','1 ano','2026-12-31','R$ 4,00 Fund. I; R$ 8,00 Fund. II, EM e curso',1912.95,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1qrrhbuflbJb1HKtBGbNhN9ZihAEr2U0A/view','https://drive.google.com/drive/folders/1rw-CN0mzYDvq8D-MppFK2tFdtg2-6zDt','[{"competencia":"2026-08","valor":1912.95,"vencimento":"2026-08-15","referencia":"731014","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|sap|barra','SAP','SAP Barra','Rio de Janeiro','Gastroservice','anaperez@gastroservice.com.br; madalena@gastroservice.com.br','21 99490-2666','Ativo','1 ano','2026-12-31','R$ 10,00 por aluno',2562.80,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/115Qgp3szq3MIV5I2DV_bsOgPUUG6PIva/view','https://drive.google.com/drive/folders/1-ikLnhkUcf1eRJQRCnbB5TNTqCmjCHS9','[{"competencia":"2026-08","valor":2562.80,"vencimento":"2026-08-15","referencia":"568056","status":"Lancado"}]',true,'["Cadastro-mestre usa Barrinha; lancamento de agosto e contrato usam Barra.","Planilha-mestra marca contrato como nao assinado, mas o contrato foi localizado no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|taquara','MATRIZ','Matriz Taquara','Rio de Janeiro','Tia Claudinha','a.claudia.bpp@gmail.com','21 99532-3725','Ativo','1 ano','2026-12-31','R$ 8,00 por aluno regular; R$ 4,00 por aluno de curso livre',2610.00,'Emissao de boleto','1a semana do mes',15,'Assinado','Informada como completa','https://drive.google.com/file/d/1OvkIBbBkucU7DUFfwVSGNA-rqJAbenfb/view','https://drive.google.com/drive/folders/1HW2lV7xTFRsaXXvpH5UFFwaDZjjPc5DT','[{"competencia":"2026-08","valor":2610.00,"vencimento":"2026-08-15","referencia":"810826","status":"Lancado"}]',false,'[]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|duque-de-caxias','MATRIZ','Matriz Duque de Caxias','Rio de Janeiro','Tia Claudinha','a.claudia.bpp@gmail.com','21 99532-3725','Ativo','1 ano','2026-12-31','R$ 8,00 por aluno regular; R$ 4,00 por aluno de curso livre',1520.00,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/10ymG_g2nVp1Hu8zWREy8NZZbaTqQveff/view','https://drive.google.com/drive/folders/1HW2lV7xTFRsaXXvpH5UFFwaDZjjPc5DT','[{"competencia":"2026-08","valor":1520.00,"vencimento":"2026-08-15","referencia":"810835","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|madureira','MATRIZ','Matriz Madureira','Rio de Janeiro','Tia Claudinha','a.claudia.bpp@gmail.com','21 99532-3725','Ativo','1 ano','2026-12-31','R$ 8,00 por aluno regular; R$ 4,00 por aluno de curso livre',1944.00,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1skAdPKWSSbByOWDpxOmS-TpOkRchSvQp/view','https://drive.google.com/drive/folders/1HW2lV7xTFRsaXXvpH5UFFwaDZjjPc5DT','[{"competencia":"2026-08","valor":1944.00,"vencimento":"2026-08-15","referencia":"810836","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|tijuca','MATRIZ','Matriz Tijuca','Rio de Janeiro','Tia Claudinha','a.claudia.bpp@gmail.com','21 99532-3725','Ativo','1 ano','2026-12-31','R$ 8,00 por aluno regular; R$ 4,00 por aluno de curso livre',778.00,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/171ZZQ_f-qHonxsEzyj_bP4WSGkxaonSH/view','https://drive.google.com/drive/folders/1HW2lV7xTFRsaXXvpH5UFFwaDZjjPc5DT','[{"competencia":"2026-08","valor":778.00,"vencimento":"2026-08-15","referencia":"810841","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|bangu','MATRIZ','Matriz Bangu','Rio de Janeiro','Elite dos Lanches','elitedoslanches2015@gmail.com; renatosantos23@gmail.com','21 96467-0234','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 2,50 por aluno de curso livre',3730.65,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1DXqHm4aul68PxK1B_y-vnriTu12RUEXs/view','https://drive.google.com/drive/folders/106HMQyeYgySvuCYIPJIvbK6PgH06laoD','[{"competencia":"2026-08","valor":3730.65,"vencimento":"2026-08-15","referencia":"810827","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|campo-grande','MATRIZ','Matriz Campo Grande','Rio de Janeiro','Elite dos Lanches','elitedoslanches2015@gmail.com; renatosantos23@gmail.com','21 96467-0234','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 2,50 por aluno de curso livre',3779.35,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1td0XmrqBbGc2MMdfkgmwoIaei35aD6Hb/view','https://drive.google.com/drive/folders/106HMQyeYgySvuCYIPJIvbK6PgH06laoD','[{"competencia":"2026-08","valor":3779.35,"vencimento":"2026-08-15","referencia":"810825","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|rocha-miranda','MATRIZ','Matriz Rocha Miranda','Rio de Janeiro','Elite dos Lanches','elitedoslanches2015@gmail.com; renatosantos23@gmail.com','21 96467-0234','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 2,50 por aluno de curso livre',2385.95,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1TsjxvqIr551jNULHHOMd8phwDCRWrYdK/view','https://drive.google.com/drive/folders/106HMQyeYgySvuCYIPJIvbK6PgH06laoD','[{"competencia":"2026-08","valor":2385.95,"vencimento":"2026-08-15","referencia":"810824","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|matriz|retiro-dos-artistas','MATRIZ','Matriz Retiro dos Artistas','Rio de Janeiro','Elite dos Lanches','elitedoslanches2015@gmail.com; renatosantos23@gmail.com','21 96467-0234','Ativo','1 ano','2026-12-31','R$ 8,40 por aluno regular; R$ 2,50 por aluno de curso livre',2444.40,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1Lufh5hQUc7j8yJprZCLF618E-796b3Rz/view','https://drive.google.com/drive/folders/106HMQyeYgySvuCYIPJIvbK6PgH06laoD','[{"competencia":"2026-08","valor":2444.40,"vencimento":"2026-08-15","referencia":"810840","status":"Lancado"}]',true,'["Cadastro-mestre usa Pechincha; contrato e lancamento de agosto usam Retiro dos Artistas."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|sa-pereira|matriz','SÁ PEREIRA','Sa Pereira Matriz','Rio de Janeiro','Alimenttar Cantinas','rafael@alimenttar.com.br','21 99214-2393','Ativo','1 ano','2026-12-31','R$ 10,00 por aluno',3065.00,'Emissao de boleto','1a semana do mes',15,'Nao confirmado','Informada como completa','','https://drive.google.com/drive/folders/1n9-SxW5O-wJ4fTXn2dXsH2P4ryCBNwbw','[{"competencia":"2026-08","valor":3065.00,"vencimento":"2026-08-15","referencia":"568050","status":"Lancado"}]',true,'["Contrato individual nao localizado no inventario atual do Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026'),
  ('cantina|leonardo-da-vinci|alfa','LEONARDO DA VINCI','Leonardo da Vinci Alfa','Porto Alegre','Malagueta','carolinerauppnutri@gmail.com','51 9788-8688','Ativo','4 anos','2026-12-31','R$ 6,00 por aluno regular; R$ 3,00 por aluno de curso',1852.40,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1TWW_jA-XTLf7xtKcV0jZWbQG2LVD1wjM/view','https://drive.google.com/drive/folders/1pQcj-m7Lieeytd0asHF2CY5uNd-1kUfL','[{"competencia":"2026-08","valor":1852.40,"vencimento":"2026-08-15","referencia":"251153","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|leonardo-da-vinci|beta','LEONARDO DA VINCI','Leonardo da Vinci Beta','Porto Alegre','Malagueta','carolinerauppnutri@gmail.com','51 9788-8688','Ativo','5 anos','2026-12-31','R$ 6,00 por aluno regular; R$ 3,00 por aluno de curso',1674.20,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1TWW_jA-XTLf7xtKcV0jZWbQG2LVD1wjM/view','https://drive.google.com/drive/folders/1pQcj-m7Lieeytd0asHF2CY5uNd-1kUfL','[{"competencia":"2026-08","valor":1674.20,"vencimento":"2026-08-15","referencia":"251155","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|leonardo-da-vinci|gama','LEONARDO DA VINCI','Leonardo da Vinci Gama','Porto Alegre','Malagueta','carolinerauppnutri@gmail.com','51 9788-8688','Ativo','6 anos','2026-12-31','R$ 6,00 por aluno regular; R$ 3,00 por aluno de curso',1007.60,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1TWW_jA-XTLf7xtKcV0jZWbQG2LVD1wjM/view','https://drive.google.com/drive/folders/1pQcj-m7Lieeytd0asHF2CY5uNd-1kUfL','[{"competencia":"2026-08","valor":1007.60,"vencimento":"2026-08-15","referencia":"60182","status":"Lancado"}]',true,'["Planilha-mestra marca contrato como nao assinado, mas ha PDF Clicksign no Drive."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|americano|porto-alegre','AMERICANO','Americano Porto Alegre','Porto Alegre','Lancheria Ralph','utopianadia@gmail.com','51 9845-4950','Ativo','1 ano','2026-12-31','R$ 6,00 por aluno regular; R$ 3,00 por aluno de curso',1440.00,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1wmfEstf3YYyNSLvk58_fMeZKm2yzQPLX/view','https://drive.google.com/drive/folders/14lF4Kpnyfehlf5UfM1Ytkqr7yW9Nat-1','[{"competencia":"2026-08","valor":1440.00,"vencimento":"2026-08-15","referencia":"15241","status":"Lancado"}]',true,'["Cadastro-mestre informa Bem Dito; contrato e lancamento de agosto informam Lancheria Ralph."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|unificado|zona-sul','UNIFICADO','Unificado Zona Sul','Porto Alegre','Lancheria Ralph','utopianadia@gmail.com','51 9845-4950','Ativo','1 ano','2026-12-31','R$ 6,00 por aluno regular; R$ 3,00 por aluno de curso',1237.50,'Emissao de boleto','1a semana do mes',15,'Encontrado no Drive','Informada como completa','https://drive.google.com/file/d/1wmfEstf3YYyNSLvk58_fMeZKm2yzQPLX/view','https://drive.google.com/drive/folders/14lF4Kpnyfehlf5UfM1Ytkqr7yW9Nat-1','[{"competencia":"2026-08","valor":1237.50,"vencimento":"2026-08-15","referencia":"142869","status":"Lancado"}]',true,'["Cadastro-mestre informa Bem Dito; lancamento de agosto informa Lancheria Ralph. Confirmar se o contrato do Americano abrange esta unidade."]','','Controle de Overdue 2026; Sublocacao Cantinas 2026; Drive'),
  ('cantina|uniao|uruguaiana','UNIÃO','Uniao Uruguaiana','Uruguaiana','Maria Clara Pellegrini','sinueloagripec@hotmail.com','51 9866-4886','Ativo','1 ano','2026-12-31','R$ 3,50 por aluno regular',0,'Emissao de boleto','1a semana do mes',15,'Nao confirmado','Informada como completa','','https://drive.google.com/drive/folders/1n9-SxW5O-wJ4fTXn2dXsH2P4ryCBNwbw','[]',true,'["Contrato individual e lancamento de agosto nao foram localizados no inventario atual."]','','Controle de Overdue 2026'),
  ('cantina|apogeu|espaco-magico-santo-antonio-1','APOGEU','Apogeu Espaco Magico Santo Antonio 1','Juiz de Fora','Vila Saudosa','administrativo@vilasaudosa.com.br','','Atencao','1 ano','2025-01-31','R$ 5,40 por lanche/colacao; R$ 7,50 por almoco/jantar',0,'Transferencia','',10,'Encontrado no Drive','Informada como incompleta','https://drive.google.com/file/d/1fCP46HXtrqi0-1e126ZbU3mAXw6FmjHZ/view','https://drive.google.com/drive/folders/1y3xoW5wX3-LpQEorakIGZsXhDXW7Cpb4','[]',true,'["Vigencia informada encerrou em 31/01/2025.","Sem lancamento de agosto localizado."]','Receber mensalmente o comprovante de repasse.','Controle de Overdue 2026; Drive'),
  ('cantina|apogeu|espaco-magico-santo-antonio-2','APOGEU','Apogeu Espaco Magico Santo Antonio 2','Juiz de Fora','Vila Saudosa','administrativo@vilasaudosa.com.br','','Atencao','1 ano','2025-01-31','R$ 5,40 por lanche/colacao; R$ 7,50 por almoco/jantar',0,'Transferencia','',10,'Encontrado no Drive','Informada como incompleta','https://drive.google.com/file/d/1fCP46HXtrqi0-1e126ZbU3mAXw6FmjHZ/view','https://drive.google.com/drive/folders/1y3xoW5wX3-LpQEorakIGZsXhDXW7Cpb4','[]',true,'["Vigencia informada encerrou em 31/01/2025.","Sem lancamento de agosto localizado."]','Receber mensalmente o comprovante de repasse.','Controle de Overdue 2026; Drive'),
  ('cantina|apogeu|cidade-alta','APOGEU','Apogeu Cidade Alta','Juiz de Fora','Vila Saudosa','administrativo@vilasaudosa.com.br','','Atencao','1 ano','2025-01-31','R$ 5,40 por lanche/colacao; R$ 7,50 por almoco/jantar',0,'Transferencia','',10,'Encontrado no Drive','Informada como incompleta','https://drive.google.com/file/d/1fCP46HXtrqi0-1e126ZbU3mAXw6FmjHZ/view','https://drive.google.com/drive/folders/1y3xoW5wX3-LpQEorakIGZsXhDXW7Cpb4','[]',true,'["Vigencia informada encerrou em 31/01/2025.","Sem lancamento de agosto localizado."]','Receber mensalmente o comprovante de repasse.','Controle de Overdue 2026; Drive'),
  ('cantina|apogeu|jardim-norte','APOGEU','Apogeu Global School Jardim Norte','Juiz de Fora','Casa da Broa','administrativo@vilasaudosa.com.br','','Atencao','1 ano',null,'Valor fixo mensal',3000.00,'Transferencia','',11,'Nao confirmado','Informada como incompleta','','https://drive.google.com/drive/folders/1n9-SxW5O-wJ4fTXn2dXsH2P4ryCBNwbw','[]',true,'["Contrato atual e lancamento de agosto nao foram localizados no inventario."]','Receber mensalmente o comprovante de repasse.','Controle de Overdue 2026'),
  ('cantina|apogeu|zona-norte','APOGEU','Apogeu Zona Norte','Juiz de Fora','Food Tuquinha','','','Atencao','1 ano',null,'Valor fixo mensal',2000.00,'Transferencia','',11,'Encontrado no Drive','Informada como incompleta','https://drive.google.com/file/d/17M39WW4v4aVlZg6etB6_RM58qFSosBG8/view','https://drive.google.com/drive/folders/1sBLmPh-EtahlQJIXPC8Oz9-JfCVHCO3C','[]',true,'["Sem lancamento de agosto localizado."]','Receber mensalmente o comprovante de repasse.','Controle de Overdue 2026; Drive'),
  ('cantina|matriz|kids','MATRIZ','Matriz Kids / Colegio Vila Valqueire','Rio de Janeiro','Colegio Vila Valqueire','','','Atencao','',null,'Cobranca mensal registrada na planilha de agosto',14935.00,'Emissao de boleto','',15,'Nao confirmado','Nao confirmado','','https://drive.google.com/drive/folders/1n9-SxW5O-wJ4fTXn2dXsH2P4ryCBNwbw','[{"competencia":"2026-08","valor":14935.00,"vencimento":"2026-08-15","referencia":"810865","status":"Lancado"}]',true,'["Lancamento atual sem correspondente no cadastro-mestre de cantinas."]','','Sublocacao Cantinas 2026'),
  ('cantina|qi|valqueire','QI','QI Valqueire','Rio de Janeiro','Alimenttar','','','Atencao','',null,'Cobranca mensal registrada na planilha de agosto',984.20,'Emissao de boleto','',15,'Nao confirmado','Nao confirmado','','https://drive.google.com/drive/folders/1n9-SxW5O-wJ4fTXn2dXsH2P4ryCBNwbw','[{"competencia":"2026-08","valor":984.20,"vencimento":"2026-08-15","referencia":"731001","status":"Lancado"}]',true,'["Lancamento atual sem correspondente no cadastro-mestre de cantinas."]','','Sublocacao Cantinas 2026')
on conflict (fonte_chave) do nothing;
