const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const css=['dashboards.css','record-cards.css','platform-usability.css'].map(f=>fs.readFileSync(path.join(root,'scripts',f),'utf8')).join('\n');
const header=i=>`<header><h2>${i===1?'Administradora de Empreendimentos e Participacoes Imobiliarias e Construcao de Unidades Escolares':'Fornecedor '+i}</h2><p>CNPJ cadastrado</p></header>`;
const values='<dl class="party-values"><div><dt>Pago registrado</dt><dd>R$ 100.000,00</dd></div><div><dt>Em aberto</dt><dd>R$ 25.000,00</dd></div></dl>';
const cards=kind=>`<div class="party-grid">${[0,1,2].map(i=>`<article class="party-card ${kind}-card">${header(i)}${values}${kind==='investor'?'<details class="party-projects"><summary>Obras vinculadas</summary><div>Obra de teste</div></details>':''}<footer><span>${i===2?'Historico de pagamentos em diversas unidades e competencias':'1 obra'}</span><button>Ver registros</button></footer></article>`).join('')}</div>`;
const metrics=`<div class="dash-metrics">${['Pago','Investimento livre depois de todas as obrigacoes contratuais cadastradas','Contratado','Saldo'].map(t=>`<div class="dash-metric"><span>${t}</span><strong>R$ 100.000,00</strong><small>Referencia registrada</small></div>`).join('')}</div>`;
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [1440,1024,768,360]){const p=await b.newPage({viewport:{width,height:960}});await p.setContent(`<style>*{box-sizing:border-box}body{margin:16px;font:14px Arial}h2{margin:0}#app>.main{min-width:0}${css}</style><div id="app"><main class="main">${metrics}${cards('supplier')}${cards('investor')}</main></div>`);
 const result=await p.evaluate(()=>{const issues=[];for(const group of document.querySelectorAll('.party-grid,.dash-metrics')){const rows=new Map();for(const card of group.children){const key=Math.round(card.getBoundingClientRect().top);if(!rows.has(key))rows.set(key,[]);rows.get(key).push(card);}for(const row of rows.values()){if(row.length<2)continue;for(const selector of group.matches('.dash-metrics')?['strong','small']:['.party-values','footer']){const positions=row.map(c=>c.querySelector(selector).getBoundingClientRect().top);if(Math.max(...positions)-Math.min(...positions)>1)issues.push({selector,positions});}}}return{issues,overflow:document.documentElement.scrollWidth>innerWidth+2};});assert.deepEqual(result.issues,[],`tracks at ${width}`);assert(!result.overflow,`overflow at ${width}`);await p.close();}console.log('PASS aligned card values, footers and dashboard metrics at 1440/1024/768/360');}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
