const test=require('node:test'),assert=require('node:assert/strict');
const d=require('./real-estate-dossier.js');
const history=(extra={})=>({id:'h1',imovel_id:'p1',periodo:'2026-08',ano:2026,tipo:'Aluguel',valor:1000,ticket_raiz:'123456',contraparte:'Locador',...extra});
const ticket=(extra={})=>({ticket_raiz:'123456',imovel_ids:['p1'],sublocacao_ids:[],financeiro:true,valor_total:1000,status:'Em andamento',anexos:[],...extra});
test('same TR from multiple workbooks is a single nominal amount',()=>{const g=d.groupHistory([history(),history({id:'h2',fonte_nome:'Outra planilha'})],[ticket()],'p1');assert.equal(g.length,1);assert.equal(g[0].sources.length,2);assert.equal(d.totals(g).total,1000);});
test('shared TR is never counted as full property expense',()=>{const g=d.groupHistory([history()],[ticket({imovel_ids:['p1','p2']})],'p1');assert.equal(g[0].value,1000);assert(g[0].shared);assert.equal(d.totals(g).total,0);});
test('conflicting source values remain visible without silently picking one',()=>{const g=d.groupHistory([history(),history({valor:1200})],[ticket()],'p1');assert(g[0].conflict);assert.equal(d.totals(g).total,0);assert.match(d.financeHtml(g),/Valores divergentes/);});
test('nominal source and Zeev total mismatch requires review',()=>{const g=d.groupHistory([history()],[ticket({valor_total:1020})],'p1');assert(g[0].conflict);assert.equal(g[0].value,1020);assert.equal(d.totals(g).total,0);});
test('legal requests do not become payable amounts',()=>assert.equal(d.groupHistory([history()],[ticket({financeiro:false})],'p1').length,0));
test('cancelled and provisional records are excluded from total',()=>{for(const [h,t]of [[history(),ticket({status:'Cancelado'})],[history({ticket_raiz:''}),null]])assert.equal(d.totals(d.groupHistory([h],t?[t]:[],'p1')).total,0);});
test('zero and unknown remain different',()=>{assert.equal(d.groupHistory([history({valor:0})],[],'p1')[0].value,0);assert.equal(d.groupHistory([history({valor:null})],[],'p1')[0].value,null);});
test('different tax registrations without TR are not merged',()=>{const rows=['111','222'].map(inscricao=>history({ticket_raiz:'',tipo:'IPTU',inscricao}));assert.equal(d.groupHistory(rows,[],'p1').length,2);});
test('multiple periods under one TR require reconciliation',()=>{const g=d.groupHistory([history(),history({periodo:'2026-09'})],[ticket()],'p1');assert(g[0].review);assert.equal(d.totals(g).total,0);});
test('renders untrusted text escaped and never emits unsafe links',()=>{const g=d.groupHistory([history({contraparte:'<script>x</script>'})],[ticket({fornecedor:'<script>x</script>',ticket_url:'javascript:bad()'})],'p1'),html=d.financeHtml(g);assert(!html.includes('<script>'));assert(!html.includes('href="javascript:'));assert(html.includes('&lt;script&gt;'));});
test('same source document from different Drive URL forms is listed once',()=>{const docs=d.documents([{url:'https://drive.google.com/file/d/abc/view',nome:'Contrato'},{url:'https://drive.google.com/file/d/abc/view?usp=sharing',nome:'Contrato'}],[]);assert.equal(docs.length,1);});
test('presence of proof filename is not a paid declaration',()=>{const html=d.financeHtml(d.groupHistory([history()],[ticket({status:'Concluido',anexos:[{nome:'comprovante.pdf',url:'https://example.com/proof.pdf'}]})],'p1'));assert(html.includes('não comprova pagamento'));assert(!html.includes('Pagamento confirmado'));});
test('blank zero placeholders are not artificial forecast entries',()=>{assert.equal(d.groupHistory([history({ticket_raiz:'',referencia:'',valor:0})],[],'p1').length,0);assert.equal(d.groupHistory([history({ticket_raiz:'',referencia:'manual',valor:0})],[],'p1').length,1);});
test('components are shown as evidence without adding to the ticket again',()=>{const g=d.groupHistory([history()],[ticket({componentes:[{tipo:'Aluguel',valor:900},{tipo:'IPTU',valor:100}]})],'p1');assert.equal(d.totals(g).total,1000);assert.match(d.financeHtml(g),/Componentes informados no TR/);assert.match(d.financeHtml(g),/900,00/);});
test('nature and year filters cannot hide divergent evidence',()=>{const g=d.groupHistory([history(),history({tipo:'IPTU',ano:2025,periodo:'2025-08',valor:1200})],[ticket()],'p1');const selected=d.selectGroups(g,{year:'2026',type:'Aluguel'});assert.equal(selected.length,1);assert(selected[0].conflict);assert.equal(selected[0].sources.length,2);assert.equal(d.totals(selected).total,0);});
test('monthly supplier and status filters apply to reconciled groups',()=>{const g=d.groupHistory([history(),history({ticket_raiz:'123457',periodo:'2026-09',contraparte:'Outro',valor:55})],[ticket()],'p1');assert.equal(d.selectGroups(g,{month:'2026-08',supplier:'Locador',state:'registered'}).length,1);assert.equal(d.selectGroups(g,{month:'2026-09',supplier:'Locador'}).length,0);assert.equal(d.selectGroups(g,{query:'123457'})[0].value,55);});
test('pagination never changes the full-recut total',()=>{const groups=Array.from({length:65},(_,i)=>({value:i+1,countable:true})),s={page:1},p=d.paginate(groups,s);assert.equal(p.rows.length,30);assert.equal(p.rows[0].value,31);assert.equal(d.totals(groups).total,2145);s.page=99;assert.equal(d.paginate(groups,s).rows.length,5);assert.equal(s.page,2);});
test('long descriptions and evidence remain in the expanded row',()=>{const text='Descricao detalhada '.repeat(100),html=d.financeHtml(d.groupHistory([history()],[ticket({descricao:text})],'p1'));assert(html.includes(text));assert(html.includes('re-payment-details'));assert(html.includes('Arquivos (0)'));assert(html.includes('Fontes (1)'));});
test('nonfinancial TR detail does not make a total or paid claim',()=>{const html=d.ticketRows([ticket({financeiro:false,status:'Finalizado'})]);assert(html.includes('Contratual / outro fluxo'));assert(!html.includes('Incluído no total nominal'));assert(!html.includes('Pagamento confirmado'));});
test('month filter uses TR competence instead of payment-workbook month when known',()=>{const groups=d.groupHistory([history({periodo:'2026-09'})],[ticket({competencia:'2026-08'})],'p1');assert.equal(d.selectGroups(groups,{month:'2026-08'}).length,1);assert.equal(d.selectGroups(groups,{month:'2026-09'}).length,0);});
test('mixed TR is split by explicit components without repeating its total',()=>{const groups=d.groupHistory([history()],[ticket({componentes:[{tipo:'Aluguel',valor:800},{tipo:'IPTU',valor:150},{tipo:'Condominio',valor:50}]})],'p1');assert.equal(d.totals(d.expenseGroups(groups,'rent')).total,800);assert.equal(d.totals(d.expenseGroups(groups,'iptu')).total,150);assert.equal(d.totals(d.expenseGroups(groups,'condo')).total,50);assert.equal(d.totals(d.expenseGroups(groups,'all')).total,1000);assert.equal(d.expenseParts(groups[0]).reduce((s,g)=>s+g.value,0),1000);});
test('IPTU and installment records stay in the property IPTU section',()=>{for(const tipo of ['IPTU','Parcelamento IPTU']){const g=d.groupHistory([history({tipo,inscricao:'123-4',periodo:'2026 / cota 03'})],[],'p1');const rows=d.expenseGroups(g,'iptu');assert.equal(rows.length,1);assert.equal(rows[0].sources[0].inscricao,'123-4');assert.match(d.financeHtml(rows),/cota 03/);assert.match(d.financeHtml(rows),/Inscrição 123-4/);}});
test('component mismatch remains unallocated, with original value intact',()=>{const g=d.groupHistory([history()],[ticket({componentes:[{tipo:'Aluguel',valor:800},{tipo:'IPTU',valor:100}]})],'p1');assert.equal(d.expenseGroups(g,'rent').length,0);assert.equal(d.expenseGroups(g,'iptu').length,0);assert.equal(d.expenseGroups(g,'unclassified')[0].value,1000);});
test('source and component category conflict is never silently classified',()=>{const g=d.groupHistory([history({tipo:'Condominio'})],[ticket({componentes:[{tipo:'Aluguel',valor:1000}]})],'p1');assert.equal(d.expenseGroups(g,'unclassified').length,1);});
test('shared and cancelled component amounts remain excluded in every section',()=>{for(const extra of [{imovel_ids:['p1','p2']},{status:'Cancelado'}]){const g=d.groupHistory([history()],[ticket({...extra,componentes:[{tipo:'Aluguel',valor:800},{tipo:'IPTU',valor:200}]})],'p1');assert.equal(d.totals(d.expenseGroups(g,'rent')).total,0);assert.equal(d.totals(d.expenseGroups(g,'iptu')).total,0);}});
test('expense projections do not mutate the original records',()=>{const g=d.groupHistory([history()],[ticket({componentes:[{tipo:'Aluguel',valor:1000}]})],'p1'),copy=JSON.stringify(g);d.expenseParts(g[0]);assert.equal(JSON.stringify(g),copy);});
test('unknown or multiple source types require classification when components are absent',()=>{const g=d.groupHistory([history(),history({tipo:'IPTU'})],[],'p1');assert.equal(d.expenseGroups(g,'unclassified').length,1);assert.equal(d.expenseGroups(g,'rent').length,0);const noSource=d.groupHistory([],[ticket()],'p1');assert.equal(d.expenseGroups(noSource,'unclassified').length,1);});
test('unrelated charges and null values are preserved',()=>{const g=d.groupHistory([history({tipo:'Seguro patrimonial',valor:null})],[],'p1');const rows=d.expenseGroups(g,'insurance');assert.equal(rows.length,1);assert.equal(rows[0].value,null);assert.match(d.financeHtml(rows),/Não informado/);});
test('fire, insurance and utilities have their own expense sections',()=>{
 for(const [tipo,section]of [['Taxa de incendio','fire'],['Seguro patrimonial','insurance'],['Agua','utilities'],['Energia','utilities'],['Gas','utilities']]){
  const g=d.groupHistory([history({tipo})],[ticket()],'p1');assert.equal(d.expenseGroups(g,section).length,1);assert.equal(d.expenseGroups(g,'other').length,0);assert.equal(d.totals(g).total,1000);
 }
});
