const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const read=file=>fs.readFileSync(path.join(__dirname,file),'utf8');
function context(profile){const c={currentProfile:profile,Date,URLSearchParams,console,document:{addEventListener(){},getElementById(){return null;}},addEventListener(){}};c.window=c;vm.createContext(c);vm.runInContext(read('access-control.js'),c);vm.runInContext(read('dashboard-hub.js'),c);return c;}
test('hub derives access from existing module grants, without granting a new permission',()=>{for(const [profile,allowed,panels]of [[null,false,0],[{role:'admin',aprovado:false},false,0],[{role:'admin',aprovado:true},true,10],[{role:'reader',aprovado:true,access_config:{}},false,0],[{role:'reader',aprovado:true,access_config:{capex:'read'}},true,1]]){const c=context(profile);assert.equal(c.AccessControl.allowedView('dashboards'),allowed);assert.equal(c.DashboardHub.available().length,panels);assert.equal(c.AccessControl.canEdit('dashboards'),false);}});
test('hub routes preserve escaped brand and unit text and ignore unrecognized parameters',()=>{const c=context({role:'admin',aprovado:true});const p=c.DashboardHub.parse('#dashboards/capex?year=2026&brand=S%C3%81+PEREIRA&unit=Recreio&role=admin');assert.equal(p.scope.brand,'SÁ PEREIRA');assert.equal(p.scope.unit,'Recreio');assert.equal(p.scope.role,undefined);assert.equal(c.DashboardHub.parse('#access_token=private'),null);assert.equal(c.DashboardHub.parse('#realestate'),null);});
test('denied panel cannot replace the selected dashboard or initiate navigation',()=>{const c=context({role:'reader',aprovado:true,access_config:{capex:'read'}});c.go=()=>assert.fail('Should not navigate');c.DashboardHub.open('realestate_locacoes');assert.equal(c.DashboardHub.panel(),'capex');});
test('hub assets and inline scripts parse',()=>{for(const f of ['dashboard-hub.js','platform-navigation.js','dashboards.js'])new vm.Script(read(f));const html=read('../index.html');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});
test('opening CAPEX historical cycles does not auto-save finalization',()=>{const html=read('../index.html'),drill=html.slice(html.indexOf('function drillCapex('),html.indexOf('function _brandSoftGradient'));assert(!drill.includes('syncCapexAutoFinalizedYear'));assert(drill.includes("capexTab='pedidos'"));});
test('dashboard consolidation introduces no mutation, email or remote sync endpoints',()=>{for(const f of ['dashboard-hub.js','platform-navigation.js'])assert(!/\.from\(|\.rpc\(|syncZeevCapexNow\(|fetch\(|sendMail\(/.test(read(f)));});
