const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const re=require('./real-estate-evidence.js');
test('document links reject unsafe protocols',()=>{for(const url of ['javascript:alert(1)','data:text/html,test','http://example.com','/relative'])assert.equal(re.safeUrl(url),'');assert.equal(re.safeUrl('https://drive.google.com/file/d/example/view'),'https://drive.google.com/file/d/example/view');});
test('document text is escaped and notes remain inspectable',()=>{const html=re.docsHtml([{url:'https://example.com',nome:'<script>bad</script>',tipo:'Contrato',contexto:'A & B',observacoes:'Clause <one>',vinculo_revisar:true}]);assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('<details>'));assert(html.includes('Vínculo a revisar'));assert(html.includes('noopener noreferrer'));});
test('missing amount is not converted to zero',()=>{assert.equal(re.money(null),'Não informado');assert.match(re.money(0),/0,00/);});
test('financial references are not labeled as Zeev tickets',()=>{const html=re.historyHtml([{periodo:'2026-08',tipo:'Cantina',valor:0,referencia:'123456',status_fonte:'Lancado',fonte_url:'https://example.com',fonte_nome:'Fonte'}]);assert(html.includes('123456'));assert(!html.includes('TR 123456'));assert.match(html,/0,00/);});
test('actual Zeev ticket and source payment status remain distinct',()=>{const html=re.historyHtml([{periodo:'2026-08',tipo:'IPTU',valor:null,ticket_raiz:'123456',data_pagamento:'2026-08-15',status_fonte:'Baixado na planilha',fonte_url:'https://example.com',fonte_nome:'Fonte'}]);assert(html.includes('TR 123456'));assert(html.includes('Baixado na planilha'));assert(html.includes('Não informado'));});
test('search normalization preserves address and identifier terms',()=>assert.equal(re.norm('São João / IPTU 012.345-6'),'sao joao iptu 012 345 6'));
test('all inline scripts parse',()=>{const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1]);assert(html.includes('realEstateNormalizeImovel({...existing,id,nome'));assert(html.includes('realestate-type-filter'));});
function saveHarness(result){const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8'),fn=html.slice(html.indexOf('async function realEstateSaveRow('),html.indexOf('async function saveRealEstateSublocacao(')),calls=[],request={};for(const method of ['update','insert','eq','is','select'])request[method]=(...args)=>(calls.push([method,...args]),request);request.single=async()=>result;const context={db:{from:()=>request}};vm.createContext(context);vm.runInContext(fn,context);return {save:context.realEstateSaveRow,calls};}
test('updates compare the original version before saving',async()=>{const h=saveHarness({data:{id:'one'}});await h.save('real_estate_imoveis',{nome:'Edited'},{id:'one',updated_at:'2026-01-01T00:00:00Z'});assert(h.calls.some(c=>c[0]==='eq'&&c[1]==='updated_at'&&c[2]==='2026-01-01T00:00:00Z'));assert(!h.calls.some(c=>c[0]==='insert'));});
test('concurrent modifications are not overwritten',async()=>{const h=saveHarness({error:{code:'PGRST116'}});await assert.rejects(()=>h.save('real_estate_imoveis',{nome:'Edited'},{id:'one',updated_at:'before'}),/outra sessao/);});
test('new records use insert and legacy null versions use null comparison',async()=>{const a=saveHarness({data:{id:'one'}});await a.save('real_estate_imoveis',{nome:'New'},null);assert(a.calls.some(c=>c[0]==='insert'));const b=saveHarness({data:{id:'one'}});await b.save('real_estate_imoveis',{}, {id:'one',updated_at:null});assert(b.calls.some(c=>c[0]==='is'&&c[1]==='updated_at'));});
